# Generated by Django 6.0.4 on 2026-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('tournament_type', models.CharField(choices=[('tree', 'Tree'), ('group', 'Group'), ('playoff', 'Group with Playoffs')], max_length=50, verbose_name='Tournament Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('division_model', models.CharField(choices=[('youth', 'Youth Divisions (U9-U19)'), ('mixed', 'Mixed Divisions (A, B, C)')], max_length=10, verbose_name='Division Model')),
                ('scoring_model', models.CharField(choices=[('best_of_3_21', 'Best of 3 sets to 21'), ('best_of_5_15', 'Best of 5 sets to 15')], default='best_of_3_21', max_length=20, verbose_name='Scoring Model')),
                ('single_match_duration', models.IntegerField(default=30, help_text='Duration of a single match in minutes', verbose_name='Single Match Duration')),
                ('double_match_duration', models.IntegerField(default=40, help_text='Duration of a double match in minutes', verbose_name='Double Match Duration')),
                ('player_break_time', models.IntegerField(default=15, help_text='Minimum break time for players between matches in minutes', verbose_name='Player Break Time')),
            ],
        ),
    ]
