# Generated by Django 6.0.4 on 2026-04-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team'),
        ('tournaments', '0002_division_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='divisions', to='players.team', verbose_name='Teams'),
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Court'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(default=1, verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='players.team', verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Time'),
        ),
    ]
