# Generated by Django 6.0.4 on 2026-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_team_player2'),
        ('tournaments', '0003_division_teams_match_court_match_match_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='discipline',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('mixed', 'Mixeddouble')], default='single', max_length=10, verbose_name='Disciplin'),
        ),
        migrations.AlterField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='divisions', to='players.team', verbose_name='Deltagere'),
        ),
    ]
