# Generated by Django 6.0.4 on 2026-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_division_discipline_alter_division_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='walkover',
            field=models.BooleanField(default=False, verbose_name='Walk-over'),
        ),
    ]
