# Generated by Django 6.0.4 on 2026-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_match_walkover'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Match Number'),
        ),
    ]
