# Generated by Django 6.0.4 on 2026-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='court_count',
            field=models.IntegerField(default=4, help_text='Antal tilgængelige baner under turneringen', verbose_name='Antal baner'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Klokkeslæt for første kamp', null=True, verbose_name='Starttidspunkt'),
        ),
    ]
