# Generated by Django 6.0.4 on 2026-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_match_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
        migrations.AddField(
            model_name='division',
            name='tournament_type',
            field=models.CharField(choices=[('group', 'Gruppe (round-robin)'), ('playoff', 'Gruppe med slutspil'), ('tree', 'Enkeltelimination')], default='group', max_length=10, verbose_name='Turneringstype'),
        ),
    ]
