# Generated by Django 6.0.4 on 2026-04-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_team_pair_type'),
        ('tournaments', '0009_remove_tournament_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_matches', to='players.team'),
        ),
    ]
