# Generated by Django 6.0.4 on 2026-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_team_pair_type'),
        ('tournaments', '0010_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bracket Label'),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_slot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bracket Slot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_matches', to='players.team'),
        ),
    ]
