# Generated by Django 6.0.4 on 2026-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_match_bracket_label_match_bracket_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='schedule_locked',
            field=models.BooleanField(default=False, help_text='Når programmet er låst, kan kampprogram og spilleplan ikke ændres.', verbose_name='Program låst'),
        ),
    ]
