# Generated by Django 6.0.4 on 2026-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_schedule_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo vises på udprintede programmer og spilleplaner.', null=True, upload_to='tournament_logos/', verbose_name='Logo'),
        ),
    ]
