# Generated by Django 6.0.4 on 2026-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_tournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='advance_count',
            field=models.IntegerField(default=2, help_text='Antal spillere/hold der går videre fra hver gruppe til slutspillet.', verbose_name='Antal der går videre'),
        ),
        migrations.AddField(
            model_name='division',
            name='group_count',
            field=models.IntegerField(default=2, help_text="Antal grupper i gruppespillet (kun ved 'Gruppe med slutspil').", verbose_name='Antal grupper'),
        ),
        migrations.AddField(
            model_name='match',
            name='group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gruppe nr.'),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Gruppespil'), ('playoff', 'Slutspil')], default='group', max_length=10, verbose_name='Fase'),
        ),
    ]
