# Generated by Django 6.0.4 on 2026-04-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_player_ranking'),
        ('tournaments', '0014_division_advance_count_division_group_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_number', models.PositiveIntegerField(verbose_name='Seedningsnummer')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='tournaments.division')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_seeds', to='players.team')),
            ],
            options={
                'ordering': ['seed_number'],
                'unique_together': {('division', 'seed_number'), ('division', 'team')},
            },
        ),
    ]
