# Generated by Django 6.0.4 on 2026-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournament_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='schedule_priority',
            field=models.IntegerField(default=5, help_text='1 = planlæg tidligst · 10 = planlæg sidst. Brug dette til at sikre at yngre rækker spiller færdigt først.', verbose_name='Spilleplansprioritet'),
        ),
    ]
