# Generated by Django 6.0.4 on 2026-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_division_schedule_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='bronze_count',
            field=models.IntegerField(default=0, help_text='0, 1 eller 2. Brug 2 ved slutspil hvor begge tabere af semifinalerne får bronce.', verbose_name='Antal broncemedaljer'),
        ),
        migrations.AddField(
            model_name='division',
            name='gold_count',
            field=models.IntegerField(default=1, help_text='Antal hold der tildeles guld (typisk 1).', verbose_name='Antal guldmedaljer'),
        ),
        migrations.AddField(
            model_name='division',
            name='silver_count',
            field=models.IntegerField(default=1, help_text='Antal hold der tildeles sølv (typisk 1).', verbose_name='Antal sølvmedaljer'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Rækkenavn'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='division_model',
            field=models.CharField(choices=[('youth', 'Ungdomsrækker (U9-U19)'), ('mixed', 'Blandede rækker (A, B, C)')], max_length=10, verbose_name='Divisionsmodel'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='double_match_duration',
            field=models.IntegerField(default=40, help_text='Varighed af en doublekamp i minutter', verbose_name='Doublekamp varighed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_break_time',
            field=models.IntegerField(default=15, help_text='Minimum hvileperiode for spillere mellem kampe i minutter', verbose_name='Spillers pausetid'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='scoring_model',
            field=models.CharField(choices=[('best_of_3_21', 'Bedst af 3 sæt til 21'), ('best_of_5_15', 'Bedst af 3 sæt til 15')], default='best_of_3_21', max_length=20, verbose_name='Scoringsmodel'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='single_match_duration',
            field=models.IntegerField(default=30, help_text='Varighed af en singlekamp i minutter', verbose_name='Singlekamp varighed'),
        ),
    ]
