# Generated by Django 6.0.4 on 2026-05-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_medal_override'),
        ('tournaments', '0018_medal_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('gold', 'Guld'), ('silver', 'Sølv'), ('bronze', 'Bronce')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_overrides', to='tournaments.division')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_overrides', to='players.team')),
            ],
            options={
                'ordering': ['medal', 'order'],
                'unique_together': {('division', 'medal', 'order')},
            },
        ),
    ]
