# Generated by Django 6.0.4 on 2026-05-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_userprofile'),
        ('tournaments', '0019_medal_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='advance_count',
            field=models.IntegerField(default=2, help_text='Number of players/teams advancing from each group to the playoff bracket.', verbose_name='Players advancing per group'),
        ),
        migrations.AlterField(
            model_name='division',
            name='bronze_count',
            field=models.IntegerField(default=0, help_text='0, 1 or 2. Use 2 for bracket tournaments where both semi-final losers receive bronze.', verbose_name='Bronze medals'),
        ),
        migrations.AlterField(
            model_name='division',
            name='discipline',
            field=models.CharField(choices=[('single', 'Singles'), ('double', 'Doubles'), ('mixed', 'Mixed doubles')], default='single', max_length=10, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='division',
            name='gold_count',
            field=models.IntegerField(default=1, help_text='Number of teams awarded gold (typically 1).', verbose_name='Gold medals'),
        ),
        migrations.AlterField(
            model_name='division',
            name='group_count',
            field=models.IntegerField(default=2, help_text="Number of groups in the group stage (only for 'Group + playoff bracket').", verbose_name='Number of groups'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Division name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='schedule_priority',
            field=models.IntegerField(default=5, help_text='1 = schedule earliest · 10 = schedule latest. Use this to ensure younger divisions finish first.', verbose_name='Schedule priority'),
        ),
        migrations.AlterField(
            model_name='division',
            name='silver_count',
            field=models.IntegerField(default=1, help_text='Number of teams awarded silver (typically 1).', verbose_name='Silver medals'),
        ),
        migrations.AlterField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='divisions', to='players.team', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='division',
            name='tournament_type',
            field=models.CharField(choices=[('group', 'Group (round-robin)'), ('playoff', 'Group + playoff bracket'), ('tree', 'Single elimination')], default='group', max_length=10, verbose_name='Tournament type'),
        ),
        migrations.AlterField(
            model_name='divisionseed',
            name='seed_number',
            field=models.PositiveIntegerField(verbose_name='Seed number'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group number'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Group stage'), ('playoff', 'Playoff bracket')], default='group', max_length=10, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='medaloverride',
            name='medal',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='court_count',
            field=models.IntegerField(default=4, help_text='Number of courts available during the tournament', verbose_name='Number of courts'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='division_model',
            field=models.CharField(choices=[('youth', 'Youth divisions (U9-U19)'), ('mixed', 'Mixed divisions (A, B, C)')], max_length=10, verbose_name='Division model'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='double_match_duration',
            field=models.IntegerField(default=40, help_text='Duration of a doubles match in minutes', verbose_name='Doubles match duration'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo is shown on printed programmes and schedules.', null=True, upload_to='tournament_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Club user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_break_time',
            field=models.IntegerField(default=15, help_text='Minimum rest period for players between matches in minutes', verbose_name='Player break time'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='schedule_locked',
            field=models.BooleanField(default=False, help_text='When locked, the match schedule cannot be changed.', verbose_name='Schedule locked'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='scoring_model',
            field=models.CharField(choices=[('best_of_3_21', 'Best of 3 sets to 21'), ('best_of_5_15', 'Best of 3 sets to 15')], default='best_of_3_21', max_length=20, verbose_name='Scoring model'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='single_match_duration',
            field=models.IntegerField(default=30, help_text='Duration of a singles match in minutes', verbose_name='Singles match duration'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time of first match', null=True, verbose_name='Start time'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('da', 'Dansk'), ('en', 'English')], default='da', max_length=10, verbose_name='Default language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
