# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='court_count',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
        migrations.CreateModel(
            name='TournamentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='1-based display number for this day.', verbose_name='Day number')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, help_text='Leave blank for unlimited ending (day runs until all matches complete).', null=True, verbose_name='End time')),
                ('court_count', models.IntegerField(default=4, help_text='Number of courts available on this day.', verbose_name='Number of courts')),
                ('buffer_minutes', models.IntegerField(default=30, help_text='Time reserved at the end of the day to absorb delays. Matches are not placed in this period.', verbose_name='Buffer (minutes)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament day',
                'verbose_name_plural': 'Tournament days',
                'ordering': ['date', 'start_time'],
                'unique_together': {('tournament', 'day_number')},
            },
        ),
        migrations.AddField(
            model_name='division',
            name='group_day',
            field=models.ForeignKey(blank=True, help_text='Day where group matches are played. Empty = scheduler decides freely.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_divisions', to='tournaments.tournamentday', verbose_name='Group phase day'),
        ),
        migrations.AddField(
            model_name='division',
            name='playoff_day',
            field=models.ForeignKey(blank=True, help_text='Day where playoff matches are played. Empty = scheduler decides freely.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playoff_divisions', to='tournaments.tournamentday', verbose_name='Playoff day'),
        ),
    ]
