from django.urls import path
from . import views

urlpatterns = [
    path('', views.tournament_list, name='tournament_list'),
    path('create/', views.tournament_create, name='tournament_create'),
    path('<int:pk>/', views.tournament_detail, name='tournament_detail'),
    path('<int:pk>/edit/', views.tournament_edit, name='tournament_edit'),
    path('<int:pk>/delete/', views.tournament_delete, name='tournament_delete'),
    path('<int:pk>/export/', views.tournament_export, name='tournament_export'),
    path('import/', views.tournament_import, name='tournament_import'),
    path('<int:tournament_pk>/division/create/', views.division_create, name='division_create'),
    path('division/<int:pk>/teams/', views.division_update_teams, name='division_update_teams'),
    path('division/<int:pk>/seeds/', views.division_update_seeds, name='division_update_seeds'),
    path('division/<int:pk>/delete/', views.division_delete, name='division_delete'),
    path('division/<int:pk>/priority/', views.division_set_priority, name='division_set_priority'),
    path('division/<int:pk>/generate/', views.division_generate_schedule, name='division_generate_schedule'),
    path('division/<int:pk>/reassign-groups/', views.division_reassign_groups, name='division_reassign_groups'),
    path('match/<int:pk>/result/', views.match_record_result, name='match_record_result'),
    path('match/<int:pk>/start/', views.match_start, name='match_start'),
    path('match/<int:pk>/postpone/', views.match_postpone, name='match_postpone'),
    path('match/<int:pk>/walkover/', views.match_walkover, name='match_walkover'),
    path('match/<int:pk>/bracket-override/', views.match_bracket_override, name='match_bracket_override'),
    path('<int:pk>/scoresheet/', views.tournament_scoresheet, name='tournament_scoresheet'),
    path('<int:pk>/wallchart/', views.tournament_wallchart, name='tournament_wallchart'),
    path('<int:pk>/court-signs/', views.tournament_court_signs, name='tournament_court_signs'),
    path('<int:pk>/program/print/', views.tournament_program_print, name='tournament_program_print'),
    path('division/<int:pk>/scoresheet/', views.division_scoresheet, name='division_scoresheet'),
    path('division/<int:pk>/medals/', views.division_medals, name='division_medals'),
    path('division/<int:pk>/medals/edit/', views.division_medals_edit, name='division_medals_edit'),
    path('division/<int:pk>/medals/reset/', views.division_medals_reset, name='division_medals_reset'),
    path('<int:pk>/schedule/', views.tournament_schedule, name='tournament_schedule'),
    path('<int:pk>/schedule/print/', views.tournament_schedule_print, name='tournament_schedule_print'),
    path('<int:pk>/schedule/generate/', views.tournament_generate_time_schedule, name='tournament_generate_time_schedule'),
    path('<int:pk>/schedule/lock/', views.tournament_toggle_lock, name='tournament_toggle_lock'),
    path('<int:pk>/schedule/reset/', views.tournament_reset_schedule, name='tournament_reset_schedule'),
    path('<int:pk>/schedule/editor/', views.schedule_editor, name='schedule_editor'),
    path('<int:pk>/schedule/suggestions/', views.schedule_suggestions, name='schedule_suggestions'),
    path('<int:pk>/schedule/assign/', views.schedule_assign, name='schedule_assign'),
    path('<int:pk>/schedule/unassign/', views.schedule_unassign, name='schedule_unassign'),
    path('<int:pk>/schedule/clear/', views.schedule_clear, name='schedule_clear'),
    path('<int:pk>/renumber/', views.tournament_renumber_matches, name='tournament_renumber_matches'),
    path('<int:pk>/renumber-by-schedule/', views.tournament_renumber_by_schedule, name='tournament_renumber_by_schedule'),
    path('<int:pk>/rebuild-playoff-labels/', views.tournament_rebuild_playoff_labels, name='tournament_rebuild_playoff_labels'),
    path('<int:pk>/bigscreen/', views.tournament_bigscreen, name='tournament_bigscreen'),
    path('<int:pk>/run/', views.tournament_run, name='tournament_run'),
]
