# Generated by Django 6.0.4 on 2026-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('ranking', models.IntegerField(verbose_name='Ranking')),
                ('division', models.CharField(choices=[('U9', 'Under 9'), ('U11', 'Under 11'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('A', 'A Række'), ('B', 'B Række'), ('C', 'C Række')], max_length=10, verbose_name='Division')),
            ],
        ),
    ]
