# Generated by Django 6.0.4 on 2026-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Mand'), ('K', 'Kvinde')], default='M', max_length=1, verbose_name='Køn'),
        ),
    ]
