# Generated by Django 6.0.4 on 2026-04-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player2', to='players.player'),
        ),
    ]
