# Generated by Django 6.0.4 on 2026-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_team_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pair_type',
            field=models.CharField(blank=True, choices=[('double', 'Double'), ('mixed', 'Mixeddouble')], help_text='Double: samme køn · Mixeddouble: et af hvert', max_length=10, null=True, verbose_name='Par-type'),
        ),
    ]
