# Generated by Django 6.0.4 on 2026-04-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_team_pair_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ranking',
        ),
    ]
