# Generated by Django 6.0.4 on 2026-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_player_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rest_until',
            field=models.DateTimeField(blank=True, help_text='Spilleren er i hvileperiode og kan ikke starte nye kampe før dette tidspunkt.', null=True, verbose_name='Hviler indtil'),
        ),
    ]
