# Generated by Django 6.0.4 on 2026-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, choices=[('U9', 'Under 9'), ('U11', 'Under 11'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('A', 'A Række'), ('B', 'B Række'), ('C', 'C Række')], max_length=10, null=True, verbose_name='Række'),
        ),
    ]
