# Generated by Django 6.0.4 on 2026-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_divisioncategory_alter_player_division_alter_team_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alder'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pair_type',
            field=models.CharField(blank=True, choices=[('double', 'Double'), ('mixed', 'Mixeddouble')], help_text='Double: samme køn · Mixeddouble: blandede', max_length=10, null=True, verbose_name='Par-type'),
        ),
    ]
