# Generated by Django 6.0.4 on 2026-05-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_medal_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisioncategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='divisioncategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_categories', to=settings.AUTH_USER_MODEL, verbose_name='Club user'),
        ),
        migrations.AlterField(
            model_name='divisioncategory',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('K', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Club user'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rest_until',
            field=models.DateTimeField(blank=True, help_text='The player is resting and cannot start new matches before this time.', null=True, verbose_name='Resting until'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pair_type',
            field=models.CharField(blank=True, choices=[('double', 'Doubles'), ('mixed', 'Mixed doubles')], help_text='Doubles: same gender · Mixed doubles: mixed gender', max_length=10, null=True, verbose_name='Pair type'),
        ),
    ]
